defaultBaseImage: gcr.io/distroless/static-debian12:nonroot

builds:
- id: cosign
  dir: .
  main: ./cmd/cosign
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  - -tags
  - "{{ .Env.GIT_HASH }}"
  - -tags
  - "{{ .Env.GIT_VERSION }}"
  ldflags:
  - -extldflags "-static"
  - "{{ .Env.LDFLAGS }}"